import { SignIn, SignedOut, SignInButton, SignOutButton, useUser, SignUpButton } from "@clerk/nextjs";
import {type NextPage} from "next";
//import x from "x";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";

const CreatePostWizard= () => {
  const {user} = useUser();
  if (!user) return null;

  return(
    <div className="flex w-full gap-3 outline-none ">
      <img src={user.profileImageUrl} 
      alt="Profile image" 
      className="h-20 w-20 rounded-full"/>
      <input placeholder="Type Some emojis!" className="grow bg-transparent"/>
    </div>
  )

 // const {mutation, isLoading} = api.posts.create.useMutation();

};

export default function Home() {

  const user = useUser();

  const { data, isLoading } = api.posts.getAll.useQuery();
  if (isLoading) return <div>Loading...</div>;
  if (!data ) return <div>"You had a spill....  Something wnet wrong"</div>;

  return (
    <>
      <Head>
        <title>gistR App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-x border-green-900 md:max-w-2xl ">
          <div className="flex border-b border-green-900 p-4">
              {!user.isSignedIn && (
                <div className="flex-justify-center">
                  <SignInButton/>
                </div>
              )}
              {user.isSignedIn && <CreatePostWizard/>}
          </div>
          <div className="flex flex-col">
            {[...data,...data,...data]?.map((post) => (
              //{data?.map((post) => (
              <div key={post.id} className="border-b border-green-900 p-8">{post.content}</div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
};


//bg-green-600